-- CHRONOS Knowledge Base Seed - 10 Personagens Históricos
-- Conteúdo verificável e academicamente fundamentado

-- 1. CLEÓPATRA VII
INSERT INTO knowledge_entries (entity_id, entity_type, nome, nome_original, periodo_historico, civilizacao, local_nascimento, local_morte, resumo, conteudo_completo, principais_feitos, influencia_historica, consenso, linha_do_tempo) VALUES
('char_cleopatra', 'character', 'Cleópatra VII', 'Κλεοπάτρα Φιλοπάτωρ', '69 a.C. – 30 a.C.', 'Egito Ptolemaico', 'Alexandria, Egito', 'Alexandria, Egito',
'Última faraó ativa do Egito Ptolemaico, governante poliglota e estrategista política que manteve a independência egípcia frente à expansão romana através de alianças com Júlio César e Marco Antônio.',
'Cleópatra VII Filopátor foi a última governante ativa da dinastia ptolemaica do Egito. Ascendeu ao trono aos 18 anos junto com seu irmão Ptolemeu XIII. Poliglota, dominava pelo menos nove idiomas, incluindo o egípcio — sendo a primeira ptolemaica a aprender a língua nativa. Sua inteligência política e diplomática lhe permitiu manter o Egito como reino independente durante um período de expansão romana agressiva. Estabeleceu alianças estratégicas com Júlio César (com quem teve um filho, Cesárion) e posteriormente com Marco Antônio (com quem teve três filhos). Após a derrota na Batalha de Áccio em 31 a.C. e a invasão romana do Egito, Cleópatra morreu em 30 a.C., encerrando três milênios de governo faraônico.',
'[{"id":"feat_1","conteudo":"Manteve a independência do Egito frente a Roma por duas décadas","confiabilidade":"fact","source_ids":[]},{"id":"feat_2","conteudo":"Poliglota: dominava egípcio, grego, latim, hebraico, aramaico e outros idiomas","confiabilidade":"fact","source_ids":[]},{"id":"feat_3","conteudo":"Reformou a economia egípcia e estabilizou a moeda","confiabilidade":"fact","source_ids":[]},{"id":"feat_4","conteudo":"Aliança política e pessoal com Júlio César e Marco Antônio","confiabilidade":"fact","source_ids":[]}]',
'Cleópatra influenciou profundamente a política mediterrânea do século I a.C. Sua morte marcou o fim do Egito como reino independente e o início de sua incorporação ao Império Romano. Sua imagem foi perpetuada na literatura, arte e cultura popular por mais de dois milênios.',
'{"resumo":"Historiadores concordam que Cleópatra foi uma líder política astuta, poliglota e administradora competente. A visão romântica popularizada por Shakespeare e Hollywood é considerada simplificação. Sua importância geopolítica para a transição República-Império Romano é amplamente reconhecida.","nivel":"fact","source_ids":[]}',
'[{"id":"tl_1","ano":-69,"titulo":"Nascimento em Alexandria","confiabilidade":"fact"},{"id":"tl_2","ano":-51,"titulo":"Ascensão ao trono com Ptolemeu XIII","confiabilidade":"fact"},{"id":"tl_3","ano":-48,"titulo":"Encontro com Júlio César","confiabilidade":"fact"},{"id":"tl_4","ano":-47,"titulo":"Nascimento de Cesárion","confiabilidade":"fact"},{"id":"tl_5","ano":-44,"titulo":"Assassinato de César; retorno ao Egito","confiabilidade":"fact"},{"id":"tl_6","ano":-41,"titulo":"Aliança com Marco Antônio","confiabilidade":"fact"},{"id":"tl_7","ano":-31,"titulo":"Derrota na Batalha de Áccio","confiabilidade":"fact"},{"id":"tl_8","ano":-30,"titulo":"Morte em Alexandria","confiabilidade":"fact"}]');

-- 2. ALEXANDRE, O GRANDE
INSERT INTO knowledge_entries (entity_id, entity_type, nome, nome_original, periodo_historico, civilizacao, local_nascimento, local_morte, resumo, conteudo_completo, principais_feitos, influencia_historica, consenso, linha_do_tempo) VALUES
('char_alexandre', 'character', 'Alexandre, o Grande', 'Ἀλέξανδρος ὁ Μέγας', '356 a.C. – 323 a.C.', 'Macedônia / Helenismo', 'Pella, Macedônia', 'Babilônia, Mesopotâmia',
'Rei da Macedônia que criou um dos maiores impérios da Antiguidade, estendendo-se da Grécia ao noroeste da Índia, difundindo a cultura helenística pelo mundo antigo.',
'Alexandre III da Macedônia, conhecido como Alexandre, o Grande, foi rei da Macedônia de 336 a.C. até sua morte. Aluno de Aristóteles, assumiu o trono aos 20 anos após o assassinato de seu pai, Filipe II. Em apenas 13 anos de reinado, conquistou o Império Persa Aquemênida, o Egito, e avançou até o rio Indo. Fundou mais de 70 cidades, incluindo Alexandria no Egito. Nunca perdeu uma batalha e é considerado um dos maiores estrategistas militares da história. Morreu aos 32 anos na Babilônia, possivelmente de febre tifoide, embora as circunstâncias exatas permaneçam debatidas.',
'[{"id":"feat_1","conteudo":"Conquista do Império Persa Aquemênida em menos de 10 anos","confiabilidade":"fact","source_ids":[]},{"id":"feat_2","conteudo":"Fundação de mais de 70 cidades, incluindo Alexandria","confiabilidade":"fact","source_ids":[]},{"id":"feat_3","conteudo":"Difusão da cultura helenística da Grécia à Índia","confiabilidade":"fact","source_ids":[]},{"id":"feat_4","conteudo":"Invicto em batalha durante toda sua carreira militar","confiabilidade":"fact","source_ids":[]}]',
'Alexandre transformou permanentemente o mundo antigo. O helenismo que difundiu criou uma cultura compartilhada no Mediterrâneo oriental e Ásia Ocidental que perdurou por séculos. Seus generais (Diádocos) fundaram dinastias que governaram por gerações, incluindo os Ptolemeus no Egito e os Selêucidas na Ásia.',
'{"resumo":"Historiadores concordam sobre a genialidade militar de Alexandre e seu papel na difusão do helenismo. Debates persistem sobre suas motivações pessoais, a natureza de sua visão de unificação cultural, e as circunstâncias de sua morte.","nivel":"fact","source_ids":[]}',
'[{"id":"tl_1","ano":-356,"titulo":"Nascimento em Pella","confiabilidade":"fact"},{"id":"tl_2","ano":-343,"titulo":"Início dos estudos com Aristóteles","confiabilidade":"fact"},{"id":"tl_3","ano":-336,"titulo":"Ascensão ao trono da Macedônia","confiabilidade":"fact"},{"id":"tl_4","ano":-334,"titulo":"Início da campanha contra a Pérsia","confiabilidade":"fact"},{"id":"tl_5","ano":-333,"titulo":"Batalha de Isso","confiabilidade":"fact"},{"id":"tl_6","ano":-331,"titulo":"Batalha de Gaugamela; queda do Império Persa","confiabilidade":"fact"},{"id":"tl_7","ano":-326,"titulo":"Batalha do Hidaspes (Índia)","confiabilidade":"fact"},{"id":"tl_8","ano":-323,"titulo":"Morte na Babilônia","confiabilidade":"fact"}]');

-- 3. JÚLIO CÉSAR
INSERT INTO knowledge_entries (entity_id, entity_type, nome, nome_original, periodo_historico, civilizacao, local_nascimento, local_morte, resumo, conteudo_completo, principais_feitos, influencia_historica, consenso, linha_do_tempo) VALUES
('char_cesar', 'character', 'Júlio César', 'Gaius Iulius Caesar', '100 a.C. – 44 a.C.', 'República Romana', 'Roma, Itália', 'Roma, Itália',
'General e estadista romano que expandiu drasticamente os territórios romanos, reformou a República e foi assassinado no Senado, precipitando a transformação de Roma em Império.',
'Gaio Júlio César foi um líder militar, político e escritor romano. Conquistou a Gália (atual França), atravessou o Rubicão desafiando o Senado, venceu a guerra civil contra Pompeu, e tornou-se ditador perpétuo. Reformou o calendário (calendário juliano), concedeu cidadania a provincianos e implementou reformas agrárias. Foi assassinado em 15 de março de 44 a.C. (Idos de Março) por um grupo de senadores liderados por Brutus e Cassius. Sua morte precipitou outra guerra civil e a eventual transformação da República Romana no Império Romano sob seu sobrinho-neto Otaviano (Augusto).',
'[{"id":"feat_1","conteudo":"Conquista da Gália (58-50 a.C.), expandindo Roma até o Atlântico","confiabilidade":"fact","source_ids":[]},{"id":"feat_2","conteudo":"Reforma do calendário romano (calendário juliano)","confiabilidade":"fact","source_ids":[]},{"id":"feat_3","conteudo":"Vitória na guerra civil contra Pompeu","confiabilidade":"fact","source_ids":[]},{"id":"feat_4","conteudo":"Reforma agrária e extensão da cidadania romana","confiabilidade":"fact","source_ids":[]}]',
'César transformou Roma irreversivelmente. Suas conquistas dobraram o território romano, suas reformas modernizaram a administração, e sua morte catalisou o fim da República. O título \"César\" tornou-se sinônimo de governante supremo em múltiplas línguas (Kaiser, Czar).',
'{"resumo":"Historiadores reconhecem César como um dos maiores generais e estadistas da Antiguidade. Há consenso sobre sua genialidade militar e impacto transformador. Debates persistem sobre se suas ações visavam monarquia pessoal ou reforma republicana genuína.","nivel":"fact","source_ids":[]}',
'[{"id":"tl_1","ano":-100,"titulo":"Nascimento em Roma","confiabilidade":"fact"},{"id":"tl_2","ano":-60,"titulo":"Primeiro Triunvirato com Pompeu e Crasso","confiabilidade":"fact"},{"id":"tl_3","ano":-58,"titulo":"Início da Guerra das Gálias","confiabilidade":"fact"},{"id":"tl_4","ano":-49,"titulo":"Travessia do Rubicão","confiabilidade":"fact"},{"id":"tl_5","ano":-48,"titulo":"Vitória sobre Pompeu em Farsália","confiabilidade":"fact"},{"id":"tl_6","ano":-46,"titulo":"Reforma do calendário","confiabilidade":"fact"},{"id":"tl_7","ano":-44,"titulo":"Assassinado nos Idos de Março","confiabilidade":"fact"}]');

-- 4. SÓCRATES
INSERT INTO knowledge_entries (entity_id, entity_type, nome, nome_original, periodo_historico, civilizacao, local_nascimento, local_morte, resumo, conteudo_completo, principais_feitos, influencia_historica, consenso, linha_do_tempo) VALUES
('char_socrates', 'character', 'Sócrates', 'Σωκράτης', '470 a.C. – 399 a.C.', 'Atenas Clássica', 'Atenas, Grécia', 'Atenas, Grécia',
'Filósofo ateniense considerado fundador da filosofia ocidental, conhecido pelo método socrático de questionamento dialético e por sua morte ao beber cicuta após condenação.',
'Sócrates foi um filósofo ateniense que não deixou escritos próprios — seu pensamento é conhecido através dos diálogos de Platão e Xenofonte. Filho de um escultor e uma parteira, desenvolveu o método dialético (maiêutica) de busca da verdade através de perguntas sistemáticas. Acreditava que a sabedoria começa com o reconhecimento da própria ignorância (\"Só sei que nada sei\"). Em 399 a.C., foi julgado e condenado por \"corromper a juventude\" e \"não reconhecer os deuses da cidade\". Recusou fugir e bebeu cicuta, transformando sua morte em ato filosófico.',
'[{"id":"feat_1","conteudo":"Criação do método socrático (maiêutica) de questionamento dialético","confiabilidade":"fact","source_ids":[]},{"id":"feat_2","conteudo":"Fundação da tradição filosófica ocidental de investigação ética","confiabilidade":"fact","source_ids":[]},{"id":"feat_3","conteudo":"Formação de Platão, que fundou a Academia","confiabilidade":"fact","source_ids":[]},{"id":"feat_4","conteudo":"Demonstração de que a filosofia pode ser prática e cotidiana","confiabilidade":"fact","source_ids":[]}]',
'Sócrates é considerado o divisor de águas da filosofia grega. Sua ênfase na ética, no autoconhecimento e no método dialético fundou a tradição filosófica ocidental. Através de Platão e Aristóteles, sua influência moldou toda a filosofia, ciência e educação posteriores.',
'{"resumo":"Há amplo consenso de que Sócrates existiu e foi uma figura central na filosofia ateniense. Historiadores reconhecem a dificuldade de separar o Sócrates histórico do personagem literário de Platão (o chamado Problema Socrático).","nivel":"fact","source_ids":[]}',
'[{"id":"tl_1","ano":-470,"titulo":"Nascimento em Atenas","confiabilidade":"fact"},{"id":"tl_2","ano":-432,"titulo":"Participação na Batalha de Potideia","confiabilidade":"fact"},{"id":"tl_3","ano":-423,"titulo":"Retratado em As Nuvens de Aristófanes","confiabilidade":"fact"},{"id":"tl_4","ano":-406,"titulo":"Membro do Conselho de Atenas","confiabilidade":"fact"},{"id":"tl_5","ano":-399,"titulo":"Julgamento, condenação e morte por cicuta","confiabilidade":"fact"}]');

-- 5. LEONARDO DA VINCI
INSERT INTO knowledge_entries (entity_id, entity_type, nome, nome_original, periodo_historico, civilizacao, local_nascimento, local_morte, resumo, conteudo_completo, principais_feitos, influencia_historica, consenso, linha_do_tempo) VALUES
('char_davinci', 'character', 'Leonardo da Vinci', 'Leonardo di ser Piero da Vinci', '1452 – 1519', 'Renascimento Italiano', 'Vinci, República de Florença', 'Amboise, França',
'Polímata italiano do Renascimento: pintor, escultor, arquiteto, engenheiro, cientista e inventor. Autor da Mona Lisa e da Última Ceia, é considerado o arquétipo do homem universal.',
'Leonardo di ser Piero da Vinci foi um polímata italiano que personificou o ideal renascentista do \"uomo universale\". Autodidata em grande parte, trabalhou em Florença, Milão, Roma e França. Seus cadernos contêm milhares de páginas com estudos de anatomia, engenharia, botânica, geologia e óptica. Como pintor, revolucionou a arte com técnicas como sfumato e chiaroscuro. Seus projetos de engenharia anteciparam invenções como o helicóptero, o tanque de guerra e o paraquedas em séculos.',
'[{"id":"feat_1","conteudo":"Pintura da Mona Lisa (c. 1503-1519) e da Última Ceia (1495-1498)","confiabilidade":"fact","source_ids":[]},{"id":"feat_2","conteudo":"Estudos anatômicos pioneiros com mais de 240 dissecções documentadas","confiabilidade":"fact","source_ids":[]},{"id":"feat_3","conteudo":"Projetos de engenharia visionários (máquinas voadoras, submarinos, pontes)","confiabilidade":"fact","source_ids":[]},{"id":"feat_4","conteudo":"Desenvolvimento do sfumato e do chiaroscuro na pintura","confiabilidade":"fact","source_ids":[]}]',
'Leonardo é considerado uma das mentes mais brilhantes da história humana. Sua obra artística definiu padrões estéticos por séculos. Seus estudos científicos anteciparam descobertas posteriores em anatomia, hidráulica e aerodinâmica.',
'{"resumo":"Historiadores da arte e da ciência concordam que Leonardo foi um gênio sem paralelo em sua época. Há consenso sobre a autenticidade de seus cadernos e sobre seu papel central no Alto Renascimento.","nivel":"fact","source_ids":[]}',
'[{"id":"tl_1","ano":1452,"titulo":"Nascimento em Vinci","confiabilidade":"fact"},{"id":"tl_2","ano":1466,"titulo":"Aprendizado no ateliê de Verrocchio em Florença","confiabilidade":"fact"},{"id":"tl_3","ano":1482,"titulo":"Mudança para Milão; trabalho para Ludovico Sforza","confiabilidade":"fact"},{"id":"tl_4","ano":1495,"titulo":"Início da Última Ceia","confiabilidade":"fact"},{"id":"tl_5","ano":1503,"titulo":"Início da Mona Lisa","confiabilidade":"fact"},{"id":"tl_6","ano":1516,"titulo":"Mudança para França a convite de Francisco I","confiabilidade":"fact"},{"id":"tl_7","ano":1519,"titulo":"Morte em Amboise, França","confiabilidade":"fact"}]');

-- 6. NAPOLEÃO BONAPARTE
INSERT INTO knowledge_entries (entity_id, entity_type, nome, nome_original, periodo_historico, civilizacao, local_nascimento, local_morte, resumo, conteudo_completo, principais_feitos, influencia_historica, consenso, linha_do_tempo) VALUES
('char_napoleao', 'character', 'Napoleão Bonaparte', 'Napoleone di Buonaparte', '1769 – 1821', 'França Revolucionária / Império Francês', 'Ajaccio, Córsega', 'Santa Helena, Atlântico Sul',
'General e imperador francês que dominou a Europa por mais de uma década, reformou as leis civis com o Código Napoleônico e redefiniu a guerra moderna.',
'Napoleão Bonaparte ascendeu durante a Revolução Francesa de oficial de artilharia a Primeiro Cônsul e depois Imperador dos Franceses. Suas campanhas militares dominaram a Europa de 1805 a 1812. O Código Napoleônico reformou o direito civil e influenciou sistemas legais em todo o mundo. Após a desastrosa campanha da Rússia, foi exilado em Elba, retornou brevemente ao poder (Cem Dias), e foi definitivamente derrotado em Waterloo (1815), sendo exilado em Santa Helena onde morreu.',
'[{"id":"feat_1","conteudo":"Promulgação do Código Napoleônico (1804), base do direito civil moderno","confiabilidade":"fact","source_ids":[]},{"id":"feat_2","conteudo":"Reorganização administrativa da França e territórios conquistados","confiabilidade":"fact","source_ids":[]},{"id":"feat_3","conteudo":"Vitórias militares em Austerlitz, Jena e Wagram","confiabilidade":"fact","source_ids":[]},{"id":"feat_4","conteudo":"Expedição científica ao Egito e decifração dos hieróglifos (Pedra de Rosetta)","confiabilidade":"fact","source_ids":[]}]',
'Napoleão transformou a Europa politicamente, juridicamente e militarmente. O Código Napoleônico influencia sistemas legais até hoje. Suas conquistas disseminaram ideais revolucionários e nacionalistas que moldaram o século XIX.',
'{"resumo":"Historiadores concordam sobre a genialidade militar e administrativa de Napoleão. Debates persistem sobre seu legado: libertador que espalhou ideais revolucionários ou tirano imperialista. Seu impacto duradouro no direito civil é indiscutível.","nivel":"fact","source_ids":[]}',
'[{"id":"tl_1","ano":1769,"titulo":"Nascimento na Córsega","confiabilidade":"fact"},{"id":"tl_2","ano":1799,"titulo":"Golpe do 18 Brumário; Primeiro Cônsul","confiabilidade":"fact"},{"id":"tl_3","ano":1804,"titulo":"Coroação como Imperador","confiabilidade":"fact"},{"id":"tl_4","ano":1805,"titulo":"Vitória em Austerlitz","confiabilidade":"fact"},{"id":"tl_5","ano":1812,"titulo":"Campanha desastrosa na Rússia","confiabilidade":"fact"},{"id":"tl_6","ano":1814,"titulo":"Primeiro exílio em Elba","confiabilidade":"fact"},{"id":"tl_7","ano":1815,"titulo":"Cem Dias e derrota em Waterloo","confiabilidade":"fact"},{"id":"tl_8","ano":1821,"titulo":"Morte em Santa Helena","confiabilidade":"fact"}]');

-- 7. CARLOS MAGNO
INSERT INTO knowledge_entries (entity_id, entity_type, nome, nome_original, periodo_historico, civilizacao, local_nascimento, local_morte, resumo, conteudo_completo, principais_feitos, influencia_historica, consenso, linha_do_tempo) VALUES
('char_carlosmagno', 'character', 'Carlos Magno', 'Carolus Magnus / Karl der Große', '742 – 814', 'Império Carolíngio', 'Provável: Aachen ou Liège', 'Aachen, Império Franco',
'Rei dos Francos e primeiro Imperador do Sacro Império Romano, unificou grande parte da Europa Ocidental e promoveu o Renascimento Carolíngio.',
'Carlos Magno (Charlemagne) foi rei dos Francos a partir de 768 e imperador dos romanos a partir de 800. Expandiu o reino franco para dominar grande parte da Europa Ocidental e Central. Promoveu reformas educacionais, religiosas e administrativas conhecidas como Renascimento Carolíngio. Estabeleceu escolas, padronizou a escrita (minúscula carolíngia) e incentivou a preservação de textos clássicos. Foi coroado imperador pelo Papa Leão III no Natal de 800, unindo autoridade temporal e espiritual.',
'[{"id":"feat_1","conteudo":"Unificação de grande parte da Europa Ocidental sob um único governo","confiabilidade":"fact","source_ids":[]},{"id":"feat_2","conteudo":"Renascimento Carolíngio: reforma educacional e preservação de textos clássicos","confiabilidade":"fact","source_ids":[]},{"id":"feat_3","conteudo":"Coroação como imperador em 800, restaurando o conceito de Império no Ocidente","confiabilidade":"fact","source_ids":[]},{"id":"feat_4","conteudo":"Padronização da escrita com a minúscula carolíngia","confiabilidade":"fact","source_ids":[]}]',
'Carlos Magno é considerado o \"Pai da Europa\". Sua unificação territorial e cultural lançou as bases para a identidade europeia medieval. O conceito de Sacro Império Romano que fundou perdurou até 1806.',
'{"resumo":"Historiadores concordam sobre o papel central de Carlos Magno na formação da Europa medieval. Debates existem sobre a extensão real do Renascimento Carolíngio e sobre suas motivações religiosas versus políticas.","nivel":"fact","source_ids":[]}',
'[{"id":"tl_1","ano":742,"titulo":"Nascimento (data exata debatida)","confiabilidade":"theory"},{"id":"tl_2","ano":768,"titulo":"Ascensão ao trono dos Francos","confiabilidade":"fact"},{"id":"tl_3","ano":774,"titulo":"Conquista do Reino Lombardo","confiabilidade":"fact"},{"id":"tl_4","ano":800,"titulo":"Coroação como imperador pelo Papa Leão III","confiabilidade":"fact"},{"id":"tl_5","ano":814,"titulo":"Morte em Aachen","confiabilidade":"fact"}]');

-- 8. RAMSÉS II
INSERT INTO knowledge_entries (entity_id, entity_type, nome, nome_original, periodo_historico, civilizacao, local_nascimento, local_morte, resumo, conteudo_completo, principais_feitos, influencia_historica, consenso, linha_do_tempo) VALUES
('char_ramses', 'character', 'Ramsés II', 'Ramesses Meryamun', 'c. 1303 a.C. – 1213 a.C.', 'Egito Antigo (Novo Império)', 'Provável: Pi-Ramsés', 'Pi-Ramsés, Egito',
'Faraó do Novo Império Egípcio, terceiro da XIX Dinastia, conhecido como \"o Grande\". Governou por 66 anos e é um dos faraós mais documentados da história.',
'Ramsés II governou o Egito por aproximadamente 66 anos (1279-1213 a.C.), um dos reinados mais longos da história egípcia. Empreendeu campanhas militares extensas, incluindo a famosa Batalha de Kadesh contra os Hititas. Construiu monumentos colossais, incluindo Abu Simbel, o Ramesseum e expansões em Karnak e Luxor. Celebrou o primeiro tratado de paz documentado da história com os Hititas. Sua múmia foi encontrada em 1881 e é uma das mais bem preservadas.',
'[{"id":"feat_1","conteudo":"Construção de Abu Simbel e do Ramesseum","confiabilidade":"fact","source_ids":[]},{"id":"feat_2","conteudo":"Primeiro tratado de paz registrado na história (com os Hititas, c. 1259 a.C.)","confiabilidade":"fact","source_ids":[]},{"id":"feat_3","conteudo":"Reinado de 66 anos com prosperidade e estabilidade","confiabilidade":"fact","source_ids":[]},{"id":"feat_4","conteudo":"Batalha de Kadesh contra o Império Hitita","confiabilidade":"fact","source_ids":[]}]',
'Ramsés II é o faraó mais associado ao apogeu do poder egípcio. Seus monumentos definiram a imagem do Egito Antigo no imaginário coletivo. O tratado egípcio-hitita é um marco na diplomacia internacional.',
'{"resumo":"Há amplo consenso sobre a grandiosidade do reinado de Ramsés II. Debates existem sobre se ele é o faraó bíblico do Êxodo (maioria dos historiadores considera improvável) e sobre a verdadeira extensão de sua vitória em Kadesh.","nivel":"fact","source_ids":[]}',
'[{"id":"tl_1","ano":-1303,"titulo":"Nascimento (data aproximada)","confiabilidade":"theory"},{"id":"tl_2","ano":-1279,"titulo":"Ascensão ao trono","confiabilidade":"fact"},{"id":"tl_3","ano":-1274,"titulo":"Batalha de Kadesh","confiabilidade":"fact"},{"id":"tl_4","ano":-1259,"titulo":"Tratado de paz com os Hititas","confiabilidade":"fact"},{"id":"tl_5","ano":-1213,"titulo":"Morte após 66 anos de reinado","confiabilidade":"fact"}]');

-- 9. GÊNGIS KHAN
INSERT INTO knowledge_entries (entity_id, entity_type, nome, nome_original, periodo_historico, civilizacao, local_nascimento, local_morte, resumo, conteudo_completo, principais_feitos, influencia_historica, consenso, linha_do_tempo) VALUES
('char_genghis', 'character', 'Gêngis Khan', 'Чингис хаан / Temüjin', 'c. 1162 – 1227', 'Império Mongol', 'Khentii, Mongólia', 'Local desconhecido (possivelmente Gansu)',
'Fundador e primeiro Grande Khan do Império Mongol, que se tornou o maior império contíguo da história. Unificou as tribos mongóis e conquistou da China ao Leste Europeu.',
'Nascido Temüjin, unificou as tribos nômades mongóis e turco-mongóis através de alianças e conquistas. Em 1206, foi proclamado Gêngis Khan (\"governante universal\") em assembleia. Construiu um exército disciplinado baseado em meritocracia e criou um sistema legal (Yasa). Conquistou a China do Norte, o Império Corásmia (Ásia Central), partes do Oriente Médio e penetrou na Europa Oriental. Seu império facilitou o comércio na Rota da Seda e promoveu tolerância religiosa. Morreu em 1227; seu túmulo nunca foi encontrado.',
'[{"id":"feat_1","conteudo":"Fundação do maior império contíguo da história (33 milhões km²)","confiabilidade":"fact","source_ids":[]},{"id":"feat_2","conteudo":"Unificação das tribos mongóis sob governo centralizado","confiabilidade":"fact","source_ids":[]},{"id":"feat_3","conteudo":"Criação do código legal Yasa e sistema postal (Yam)","confiabilidade":"fact","source_ids":[]},{"id":"feat_4","conteudo":"Promoção de tolerância religiosa e meritocracia","confiabilidade":"fact","source_ids":[]}]',
'Gêngis Khan conectou Oriente e Ocidente como nunca antes. A Pax Mongolica facilitou comércio, transferência de tecnologia e intercâmbio cultural ao longo da Rota da Seda. Estima-se que 0.5% da população mundial atual descende dele.',
'{"resumo":"Historiadores reconhecem Gêngis Khan como um dos conquistadores mais eficazes da história e um administrador inovador. Debates persistem sobre o custo humano de suas conquistas (estimativas variam de 5% a 10% da população mundial) versus seus benefícios civilizacionais.","nivel":"fact","source_ids":[]}',
'[{"id":"tl_1","ano":1162,"titulo":"Nascimento como Temüjin (data debatida)","confiabilidade":"theory"},{"id":"tl_2","ano":1206,"titulo":"Proclamação como Gêngis Khan","confiabilidade":"fact"},{"id":"tl_3","ano":1211,"titulo":"Invasão da China Jin","confiabilidade":"fact"},{"id":"tl_4","ano":1219,"titulo":"Conquista do Império Corásmia","confiabilidade":"fact"},{"id":"tl_5","ano":1227,"titulo":"Morte durante campanha contra Xi Xia","confiabilidade":"fact"}]');

-- 10. WINSTON CHURCHILL
INSERT INTO knowledge_entries (entity_id, entity_type, nome, nome_original, periodo_historico, civilizacao, local_nascimento, local_morte, resumo, conteudo_completo, principais_feitos, influencia_historica, consenso, linha_do_tempo) VALUES
('char_churchill', 'character', 'Winston Churchill', 'Winston Leonard Spencer-Churchill', '1874 – 1965', 'Império Britânico / Reino Unido', 'Palácio de Blenheim, Oxfordshire', 'Londres, Inglaterra',
'Primeiro-ministro britânico durante a Segunda Guerra Mundial, orador extraordinário e líder que galvanizou a resistência britânica contra o nazismo. Prêmio Nobel de Literatura.',
'Winston Churchill serviu como Primeiro-Ministro do Reino Unido de 1940 a 1945 e novamente de 1951 a 1955. Antes da guerra, teve carreira variada como jornalista, militar, e político em diversos ministérios. Como PM durante a Segunda Guerra, seus discursos inspiraram a resistência britânica quando a Grã-Bretanha enfrentava a Alemanha nazista praticamente sozinha em 1940-41. Ganhou o Prêmio Nobel de Literatura em 1953 por suas obras históricas e biográficas. Foi também pintor amador prolífico.',
'[{"id":"feat_1","conteudo":"Liderança britânica durante a Segunda Guerra Mundial","confiabilidade":"fact","source_ids":[]},{"id":"feat_2","conteudo":"Discursos que galvanizaram a resistência: Blood, Toil, Tears and Sweat; We Shall Fight on the Beaches","confiabilidade":"fact","source_ids":[]},{"id":"feat_3","conteudo":"Prêmio Nobel de Literatura (1953)","confiabilidade":"fact","source_ids":[]},{"id":"feat_4","conteudo":"Papel na conferência de Yalta e na definição da ordem pós-guerra","confiabilidade":"fact","source_ids":[]}]',
'Churchill é amplamente considerado um dos líderes mais importantes do século XX. Sua recusa em negociar com Hitler em 1940 é vista como um dos momentos decisivos da história moderna. Seus escritos e discursos moldaram a narrativa da guerra.',
'{"resumo":"Há amplo consenso sobre o papel crucial de Churchill na vitória aliada. Debates persistem sobre suas posições sobre o colonialismo, a Índia, e decisões controversas como o bombardeio de Dresden e a fome de Bengala (1943).","nivel":"fact","source_ids":[]}',
'[{"id":"tl_1","ano":1874,"titulo":"Nascimento no Palácio de Blenheim","confiabilidade":"fact"},{"id":"tl_2","ano":1900,"titulo":"Eleito para o Parlamento pela primeira vez","confiabilidade":"fact"},{"id":"tl_3","ano":1940,"titulo":"Torna-se Primeiro-Ministro","confiabilidade":"fact"},{"id":"tl_4","ano":1945,"titulo":"Vitória na Europa; perde eleição","confiabilidade":"fact"},{"id":"tl_5","ano":1951,"titulo":"Segundo mandato como PM","confiabilidade":"fact"},{"id":"tl_6","ano":1953,"titulo":"Prêmio Nobel de Literatura","confiabilidade":"fact"},{"id":"tl_7","ano":1965,"titulo":"Morte em Londres","confiabilidade":"fact"}]');
